"""Incident & Evidence Report generator.

Produces a structured PDF plus a zipped evidence package with a manifest of
SHA-256 hashes. The document is explicitly not a police report and says so.
"""
from __future__ import annotations

import json
import zipfile
from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from sqlalchemy.orm import Session

from app.config import settings
from app.models import Incident, RefundRequest, Report, RiskAssessment, Transaction
from app.services import evidence_service, incident_service

INK = colors.HexColor("#10233A")
SLATE = colors.HexColor("#5A6A7D")
LINE = colors.HexColor("#D6DEE8")
CRITICAL = colors.HexColor("#C0342B")
BAND = colors.HexColor("#EEF3F9")

DISCLAIMER = (
    "This document is a structured evidence summary generated by Retrace. It is not an "
    "official police report, a legal opinion, or a determination of fraud. Risk scores are "
    "produced by rule-based and demonstration machine-learning components and indicate patterns "
    "that warrant review, not proof of wrongdoing."
)


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "brand": ParagraphStyle(
            "brand", parent=base["Title"], fontName="Helvetica-Bold", fontSize=26,
            textColor=INK, spaceAfter=2, alignment=TA_LEFT, leading=30,
        ),
        "doctype": ParagraphStyle(
            "doctype", parent=base["Normal"], fontName="Helvetica", fontSize=13,
            textColor=SLATE, spaceAfter=14, leading=17,
        ),
        "h2": ParagraphStyle(
            "h2", parent=base["Heading2"], fontName="Helvetica-Bold", fontSize=11.5,
            textColor=INK, spaceBefore=15, spaceAfter=6, leading=14,
        ),
        "body": ParagraphStyle(
            "body", parent=base["Normal"], fontName="Helvetica", fontSize=9.5,
            textColor=colors.HexColor("#22303F"), leading=14, spaceAfter=5,
        ),
        "small": ParagraphStyle(
            "small", parent=base["Normal"], fontName="Helvetica", fontSize=8,
            textColor=SLATE, leading=11,
        ),
        "mono": ParagraphStyle(
            "mono", parent=base["Normal"], fontName="Courier", fontSize=8, leading=11,
            textColor=colors.HexColor("#22303F"),
        ),
        "quote": ParagraphStyle(
            "quote", parent=base["Normal"], fontName="Helvetica-Oblique", fontSize=9.5,
            leading=14, leftIndent=10, textColor=colors.HexColor("#3A4A5C"),
        ),
    }


def _kv_table(rows: list[tuple[str, str]], styles) -> Table:
    data = [[Paragraph(k, styles["small"]), Paragraph(v or "—", styles["body"])] for k, v in rows]
    table = Table(data, colWidths=[52 * mm, 108 * mm], hAlign="LEFT")
    table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LINEBELOW", (0, 0), (-1, -2), 0.4, LINE),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("LEFTPADDING", (0, 0), (0, -1), 0),
            ]
        )
    )
    return table


def _fmt(dt: datetime | None) -> str:
    return dt.strftime("%d %b %Y, %H:%M") if dt else "—"


def _money(value: float | None) -> str:
    return f"Rs {value:,.0f}" if value is not None else "—"


def build_pdf(db: Session, incident: Incident) -> Path:
    styles = _styles()
    reference = f"{incident.case_id}-{datetime.now().strftime('%Y%m%d%H%M%S')}"
    path = settings.reports_dir / f"incident-report-{reference}.pdf"

    transaction = db.get(Transaction, incident.transaction_id) if incident.transaction_id else None
    refund = (
        db.get(RefundRequest, incident.refund_request_id) if incident.refund_request_id else None
    )
    assessment = (
        db.query(RiskAssessment)
        .filter(RiskAssessment.transaction_id == (transaction.id if transaction else None))
        .order_by(RiskAssessment.created_at.desc())
        .first()
    )
    stats = incident_service.completeness(db, incident.id, incident.user_id)
    files = [e for e in incident.evidence if not e.placeholder]

    story: list = []
    story.append(Paragraph("Retrace", styles["brand"]))
    story.append(Paragraph("Incident &amp; Evidence Report", styles["doctype"]))
    story.append(HRFlowable(width="100%", thickness=1.1, color=INK, spaceAfter=12))

    story.append(
        _kv_table(
            [
                ("Case ID", incident.case_id),
                ("Report reference", reference),
                ("Generated", _fmt(datetime.now())),
                ("Incident date", _fmt(incident.created_at)),
                ("Status", incident.status.replace("_", " ").title()),
                ("Account holder", incident.user.full_name if incident.user else "—"),
            ],
            styles,
        )
    )

    story.append(Paragraph("1. Incident summary", styles["h2"]))
    story.append(Paragraph(incident.summary or "—", styles["body"]))

    story.append(Paragraph("2. Original transaction", styles["h2"]))
    if transaction:
        story.append(
            _kv_table(
                [
                    ("Transaction ID", transaction.reference),
                    ("Date and time", _fmt(transaction.created_at)),
                    ("Amount", _money(transaction.amount)),
                    ("Sender", transaction.sender_handle),
                    ("Receiver", transaction.receiver_handle),
                    ("Payment method", transaction.payment_method),
                    ("Status", transaction.status),
                ],
                styles,
            )
        )
    else:
        story.append(Paragraph("No linked transaction on record.", styles["body"]))

    story.append(Paragraph("3. Refund transaction", styles["h2"]))
    if refund:
        story.append(
            _kv_table(
                [
                    ("Refund reference", refund.reference),
                    ("Amount", _money(refund.amount)),
                    ("Requested via", refund.channel.title()),
                    ("Time after credit", f"{max(round(refund.seconds_since_payment / 60), 1)} minute(s)"),
                    ("Original sender", refund.original_sender),
                    ("Refund destination", refund.refund_destination),
                    (
                        "Destination match",
                        "Same as sender" if refund.destination_matches_sender
                        else "Different from the original sender",
                    ),
                    ("Outcome", refund.status.replace("_", " ").title()),
                ],
                styles,
            )
        )
    else:
        story.append(Paragraph("No refund request on record.", styles["body"]))

    story.append(Paragraph("4. Suspect information", styles["h2"]))
    story.append(
        _kv_table(
            [
                ("UPI handle used to pay in", incident.suspect_handle or "—"),
                ("Refund handle supplied", refund.refund_destination if refund else "—"),
                (
                    "Sender account age",
                    f"about {transaction.sender_account_age_days} days" if transaction else "—",
                ),
                (
                    "Earlier reports on this handle",
                    str(transaction.sender_prior_reports) if transaction else "—",
                ),
            ],
            styles,
        )
    )

    story.append(Paragraph("5. Incident timeline", styles["h2"]))
    if incident.events:
        rows = [
            [
                Paragraph(_fmt(e.occurred_at), styles["small"]),
                Paragraph(f"<b>{e.title}</b><br/>{e.detail or ''}", styles["body"]),
            ]
            for e in sorted(incident.events, key=lambda e: e.occurred_at)
        ]
        table = Table(rows, colWidths=[36 * mm, 124 * mm], hAlign="LEFT")
        table.setStyle(
            TableStyle(
                [
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LINEBELOW", (0, 0), (-1, -2), 0.4, LINE),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("LEFTPADDING", (0, 0), (0, -1), 0),
                ]
            )
        )
        story.append(table)
    else:
        story.append(Paragraph("No timeline events recorded.", styles["body"]))

    story.append(PageBreak())

    story.append(Paragraph("6. Message transcript", styles["h2"]))
    if incident.scam_message:
        story.append(Paragraph(incident.scam_message.replace("\n", "<br/>"), styles["quote"]))
    else:
        story.append(Paragraph("No message was preserved with this incident.", styles["body"]))

    story.append(Paragraph("7. Risk assessment", styles["h2"]))
    story.append(
        _kv_table(
            [
                ("Combined risk score", f"{incident.risk_score} / 100"),
                ("Refund safety score", f"{100 - incident.risk_score} / 100"),
                ("Risk level", incident.risk_level),
                ("Rules engine", f"{assessment.rule_score} / 100" if assessment else "—"),
                (
                    "Demo ML probability",
                    f"{round(assessment.ml_probability * 100)}%" if assessment else "—",
                ),
                ("Message analysis", f"{assessment.message_score} / 100" if assessment else "—"),
                ("Network analysis", f"{assessment.network_score} / 100" if assessment else "—"),
            ],
            styles,
        )
    )
    if assessment and assessment.signals:
        story.append(Spacer(1, 5))
        story.append(Paragraph("Contributing signals", styles["small"]))
        signal_rows = [
            [
                Paragraph(f"{'+' if s.weight >= 0 else ''}{s.weight}", styles["mono"]),
                Paragraph(f"{s.label}<br/><font size=7 color='#5A6A7D'>{s.detail or ''}</font>", styles["body"]),
            ]
            for s in sorted(assessment.signals, key=lambda s: -s.weight)
        ]
        table = Table(signal_rows, colWidths=[14 * mm, 146 * mm], hAlign="LEFT")
        table.setStyle(
            TableStyle(
                [
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ("LEFTPADDING", (0, 0), (0, -1), 0),
                ]
            )
        )
        story.append(table)

    story.append(Paragraph("8. Evidence index", styles["h2"]))
    story.append(
        Paragraph(
            f"Completeness {stats['percent']}% — {stats['total_files']} file(s) preserved.",
            styles["small"],
        )
    )
    story.append(Spacer(1, 4))
    if files:
        header = [
            Paragraph("#", styles["small"]),
            Paragraph("Evidence", styles["small"]),
            Paragraph("Original filename", styles["small"]),
            Paragraph("SHA-256", styles["small"]),
        ]
        rows = [header]
        for idx, item in enumerate(files, start=1):
            rows.append(
                [
                    Paragraph(f"{idx:02d}", styles["mono"]),
                    Paragraph(item.label, styles["body"]),
                    Paragraph(item.original_filename or "—", styles["small"]),
                    Paragraph(item.sha256 or "—", styles["mono"]),
                ]
            )
        table = Table(rows, colWidths=[10 * mm, 46 * mm, 40 * mm, 64 * mm], hAlign="LEFT", repeatRows=1)
        table.setStyle(
            TableStyle(
                [
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("BACKGROUND", (0, 0), (-1, 0), BAND),
                    ("LINEBELOW", (0, 0), (-1, -1), 0.4, LINE),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ]
            )
        )
        story.append(table)
    else:
        story.append(Paragraph("No files have been preserved for this case yet.", styles["body"]))

    if stats["missing"]:
        story.append(Spacer(1, 6))
        story.append(
            Paragraph(
                "Still missing: " + ", ".join(stats["missing"]),
                ParagraphStyle("missing", parent=styles["small"], textColor=CRITICAL),
            )
        )

    story.append(Paragraph("9. Bank complaint", styles["h2"]))
    story.append(
        _kv_table([("Complaint reference", incident.bank_complaint_ref or "Not recorded")], styles)
    )

    story.append(Paragraph("10. Additional notes", styles["h2"]))
    story.append(Paragraph(incident.notes or "None.", styles["body"]))

    story.append(Spacer(1, 16))
    story.append(
        KeepTogether(
            [
                HRFlowable(width="100%", thickness=0.7, color=LINE, spaceAfter=8),
                Paragraph("Disclaimer", styles["small"]),
                Paragraph(DISCLAIMER, styles["small"]),
            ]
        )
    )

    def _footer(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(SLATE)
        canvas.drawString(20 * mm, 12 * mm, f"Retrace · {incident.case_id} · not an official police report")
        canvas.drawRightString(190 * mm, 12 * mm, f"Page {doc.page}")
        canvas.restoreState()

    doc = SimpleDocTemplate(
        str(path),
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=18 * mm,
        bottomMargin=20 * mm,
        title=f"Retrace Incident & Evidence Report {incident.case_id}",
        author="Retrace",
    )
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return path


def build_package(db: Session, incident: Incident, pdf_path: Path) -> Path:
    """Bundle the report, every preserved file and a manifest into one zip."""
    stats = incident_service.completeness(db, incident.id, incident.user_id)
    files = [e for e in incident.evidence if not e.placeholder and e.stored_filename]
    package_path = settings.reports_dir / f"evidence-package-{incident.case_id}.zip"

    manifest = {
        "case_id": incident.case_id,
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "status": incident.status,
        "risk_score": incident.risk_score,
        "risk_level": incident.risk_level,
        "potential_loss": incident.potential_loss,
        "suspect_handle": incident.suspect_handle,
        "evidence_completeness_percent": stats["percent"],
        "missing_evidence": stats["missing"],
        "report": pdf_path.name,
        "files": [],
        "disclaimer": DISCLAIMER,
    }

    with zipfile.ZipFile(package_path, "w", zipfile.ZIP_DEFLATED) as bundle:
        bundle.write(pdf_path, "incident-report.pdf")
        for idx, item in enumerate(files, start=1):
            arc = f"evidence/{idx:02d}-{evidence_service.safe_filename(item.original_filename or item.label)}"
            verified = False
            try:
                source = evidence_service.path_for(item.stored_filename)
                bundle.write(source, arc)
                verified = evidence_service.verify_hash(item.stored_filename, item.sha256)
            except Exception:
                arc = None  # file no longer on disk; recorded in the manifest as missing
            manifest["files"].append(
                {
                    "index": idx,
                    "label": item.label,
                    "category": item.category,
                    "type": item.evidence_type,
                    "original_filename": item.original_filename,
                    "path_in_package": arc,
                    "size_bytes": item.size_bytes,
                    "sha256": item.sha256,
                    "hash_verified_at_packaging": verified,
                    "uploaded_at": item.uploaded_at.isoformat(timespec="seconds"),
                }
            )
        bundle.writestr("manifest.json", json.dumps(manifest, indent=2))

    return package_path


def generate(db: Session, incident: Incident, include_package: bool = True) -> Report:
    pdf_path = build_pdf(db, incident)
    package_path = build_package(db, incident, pdf_path) if include_package else None
    stats = incident_service.completeness(db, incident.id, incident.user_id)

    report = Report(
        incident_id=incident.id,
        user_id=incident.user_id,
        reference=pdf_path.stem.replace("incident-report-", ""),
        pdf_filename=pdf_path.name,
        package_filename=package_path.name if package_path else None,
        evidence_count=stats["total_files"],
        completeness=stats["percent"],
    )
    db.add(report)
    if incident.status == "OPEN":
        incident.status = "REPORT_READY"
    incident_service.add_event(
        db, incident, "Incident & Evidence Report generated",
        f"{stats['total_files']} file(s) indexed at {stats['percent']}% completeness.",
    )
    db.flush()
    return report
